config/routes.rb
Rails.application.routes.draw do

  post 'bookings/checkout'

  get 'driver/apply'

  resource :bookings

  devise_for :users, :controllers => { :registrations => :registrations }
  
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

	# every booking has a pick and drop off detail
	has_many :delivery_details
	accepts_nested_attributes_for :delivery_details

	#every booking has one tracking detail
	has_one :tracking_detail 
	accepts_nested_attributes_for :tracking_detail 

	#payment ref
	has_one :payment_detail
	accepts_nested_attributes_for :payment_detail 

	#each booking must be associated to a user
	belongs_to :user


	#return pickup address
    def is_pickUp(book)
    	
    	#get the pickup address for this booking
    	address=DeliveryDetail.new
    	address.find_by(booking_id: book, the_pickup: true)
  

    end

end

app/models/delivery_detail.rb
class DeliveryDetail < ApplicationRecord

	belongs_to :booking

	#validate phone numbers
	#validates :delivery_phone_number, format: { with: 0-9,
    #message: "only numbers allowed" }

    
	
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord

	belongs_to :booking	
end

app/models/tracking_detail.rb
class TrackingDetail < ApplicationRecord

	belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :confirmable

         #every user can book many deliveries
         has_many :booking
        # accepts_nested_attributes_for :booking

        #add user to mailing list
  		# before_create :subscribeToMail


private 

	#def subscribeToMail

    #    begin
  			
	#	rescue Gibbon::MailChimpError => e
  			#puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
	#	end
	
	#end

end #end model

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :business_name, :contact_number, :email, :password ])
            devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :business_name, :contact_number, :email, :password, :current_password ])
        end

        # set page for sign in
        def after_sign_in_path_for(resource)

      		bookings_path
    	end

    	#set page for sign out go to home page
    	def after_sign_out_path_for(resource_or_scope)

  			root_path

		end
end

 #devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

app/controllers/bookings_controller.rb
require 'rubygems'
require 'excon'
require 'multi_json'

class BookingsController < ApplicationController
  
  #user must be logged in before seeing this page
  before_action :authenticate_user!

  def show
		#pass all model bookings for this user
  end

  def new
	 #just load the new view
  end

  def create
    #show some kind of spinner to indicate processing

    #process payment and save booking in db

    #create json to be sent,

    #use connection to post then persistent =false
  	
  end

  def checkout

    #show some kind of spinner to indicate processing

    #take param data from form 

    @partialbooking=current_user.booking.create(item_description: params[:item_descript], delivery_instructions: params[:delivery_instruct])

    @pickUp= @partialbooking.delivery_details.create(delivery_name: params[:pick_name],
    delivery_address: params[:pick_address], delivery_phone_number: params[:pick_phone], the_pickup: true)

    @dropOff= @partialbooking.delivery_details.create(delivery_name: params[:drop_name],
    delivery_address: params[:drop_address], delivery_phone_number: params[:drop_phone] )
  
    #get swift api key for json builder
    swift_key=Rails.application.secrets.key_getswift_api.to_s

    #create json to be sent, its not at all pretty but will do for now    
    pdetailll=Jbuilder.new do |p|     
        p.address @pickUp.delivery_address.to_s
    end
    ddetailll=Jbuilder.new do |d|     
        d.address @dropOff.delivery_address.to_s
    end  
    bookkk= Jbuilder.new do |booking|     
        booking.pickupDetail pdetailll
        booking.dropoffDetail ddetailll
    end      
    jsonquote=Jbuilder.new do |quote|
      quote.apiKey swift_key.to_s
      quote.booking bookkk
    end

    #render  plain: jsonquote.target!.to_s

    #create excon connection for server use & get quote
     @connection = Excon.new('https://app.getswift.co', :persistent => true)
     @connection.request(:idempotent => true)
     logger.info "connection sorted" 
     post_response = @connection.post(:path => '/api/v2/quotes', :body => jsonquote.target!.to_s, :headers => { "Content-Type" => "application/json"})
      
      #log request details
      logger.info " Sending API request"
      logger.info " API response "
      logger.info post_response.status 

      #add error handling here  ----
      if response.status == 200

         logger.info "parsing body "
         #parse the body 

         begin
            
            @parse=MultiJson.load(post_response.body)

            #update partial booking and pass to view
            @partialbooking.delivery_distance=@parse['quote']['distanceKm']
            @partialbooking.delivery_price=@parse['quote']['fee']['cost'].to_d
            @partialbooking.delivery_price_cents=@parse['quote']['fee']['costCents'].to_i
            @pickUp.delivery_best_possible_time=@parse['quote']['pickup']['time']['average']
            @dropOff.delivery_best_possible_time=@parse['quote']['dropoff']['time']['average']


        rescue MultiJson::ParseError => exception
            exception.data 
            exception.cause 
        end

      end #end reponse if
      logger.info "success "

    #loads checkoutpage with data
    
  end


  private


      #validate params individually
     def article_params

      params.require(:deliverydetail).permit(:pick_phone, :pick_address, :pick_name)
  
    end



end #end class

app/controllers/driver_controller.rb
class DriverController < ApplicationController
 
	
  def apply
  	#this loads driver form
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  
	#user must be logged in before seeing this page
  before_action :authenticate_user!

  def index

  	#pass current user to view
  	@tuser=current_user

  	#access the model for previous deliveries, pass it to the index view

  end


  def create
  	
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

protected

    def after_update_path_for(resource)
      edit_user_registration_path(resource)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	#show main page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/checkout.html.erb
<!-- <div class="turbolinks-progress-bar">
      Progress bar 

</div> -->


	<div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Delivery Summary</span>
            <span class="badge badge-secondary badge-pill"><%= @partialbooking.delivery_distance  %> km</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Pick up details</h6>
                <small class="text-muted"><%= @pickUp.delivery_name %>, <%= @pickUp.delivery_phone_number %></small>
              </div>
              <span class="text-muted"><%= @pickUp.delivery_address%></span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Drop off details</h6>
                <small class="text-muted"><%=  @dropOff.delivery_name %>, <%= @dropOff.delivery_phone_number %></small>
              </div>
              <span class="text-muted"><%= @dropOff.delivery_address%></span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Description</h6>
                <small class="text-muted"><%= @partialbooking.item_description %></small>
              </div>
            </li>
        
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (TTD)</span>
              <strong>$ <%= @partialbooking.delivery_price %></strong>
            </li>
          </ul>

         
        </div>

  </div>

 <h4 class="mb-3">Payment Details</h4>

            

app/views/bookings/new.html.erb
<h2>Book Delivery<span class="label label-default"></span></h2>



<%= form_tag({controller: "bookings", action: "checkout"}, method: "post")  do %>
  

<p>
  <a class="btn btn-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
     Enter Pick Up
  </a>
</p>

<div class="collapse" id="collapseExample">
  <div class="card card-body">
   
 
  <div class="form-group">
    <label class="control-label" for="pick_name"> Name </label>
    <%= text_field_tag :pick_name, current_user.first_name.to_s.concat(' ').concat(current_user.last_name.to_s), class: 'form-control', placeholder: "Enter Name", required: true %>
  </div>

 
   <div class="form-group">
   		<label class="control-label" for="pick_address">Address</label>
      <%= text_field_tag :pick_address, '', class: 'form-control', placeholder: "Please enter pickup address.", required: true %>
  </div>

 	<div class="form-group">
   		<label class="control-label" for="pick_phone">Number</label>
      <%= text_field_tag :pick_phone, current_user.contact_number, class: 'form-control', placeholder: "+1 (ddd) ddd-dddd", required: true %>
  		
	 </div>   

 </div>

</div> <!-- end pick up collapse-->


<p>
  <a class="btn btn-link" data-toggle="collapse" href="#dropCollapse" role="button" aria-expanded="true" aria-controls="dropCollapse">
     Enter Drop off 
  </a>
</p>


<div class="collapse" id="dropCollapse">
  <div class="card card-body">
 

  <div class="form-group">
    <label class="control-label" for="drop_name"> Name </label>
    <%= text_field_tag :drop_name, '', class: 'form-control', placeholder: "Enter name of person to collect", required: true %>
  </div>

   <div class="form-group">
   		<label class="control-label" for="drop_address">Address</label>
      <%= text_field_tag :drop_address, '', class: 'form-control', placeholder: "Please enter drop off address.", required: true %>
  </div>

 	<div class="form-group">
   		<label class="control-label" for="drop_phone">Number </label>
      <%= text_field_tag :drop_phone, '', class: 'form-control', placeholder: "+1 (ddd) ddd-dddd", required: true %>
	 </div>

	  </div>
</div> <!-- drop off collapse-->  


	<div class="form-group">
    <label for="item_descript">Item description</label>

    <%= text_area_tag(:item_descript, '', rows: 5, class: 'form-control',  placeholder: "Clearly describe the items to be delivered", required: true) %>
  </div>

  <div class="form-group">
    <label for="delivery_instruct">Delivery Instructions</label>
    <%= text_area_tag(:delivery_instruct, '', rows: 5, class: 'form-control',  placeholder: "Any instructions for the driver?", required: false) %>
  </div>


  <%= submit_tag "Book", class: "btn btn-default" %>   
   

<% end %>

app/views/bookings/show.html.erb
 <a><%= link_to "New Delivery", new_bookings_path  %></a> 


<h2> Current deliveries</h2>
<p>you can edit these up to 2 hrs before</p>


<h2>Past deliveries</h2>
<p>you cant edit these</p>

app/views/driver/apply.html.erb
<div class="container-fluid"> 
  <h2 class="display-4">Want to become family?</h2>
  
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Apply Now</a>
  </p>
</div>


<div class="container-fluid">
  
<!--<img src="..." class="rounded float-left" alt="...">
<img src="..." class="rounded float-right" alt="..."> -->


</div>



<div class="container-fluid"> 
  <h2 class="display-4">Join the family?</h2>
   <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Apply Now</a>
  </p> 
  <hr class="my-4">
  <p>Island Dropper is about more than deliveries. Whether you're looking to pay bills or fund dreams,we will get you there.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Island Dropper" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <!-- dirty way to add this butt -->
     <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<% Rails.application.secrets.key_google_places%>&libraries=places"></script>-->

     <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
     

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

         <% if user_signed_in? %>
         <%= link_to 'ISLAND DROPPER', bookings_path, :class => 'navbar-brand' %> 
          <% else %> 
          <%= link_to 'ISLAND DROPPER', root_path, :class => 'navbar-brand' %> 
          <% end %>   
        <!-- <a class="navbar-brand" href="root_path">ISLAND DROPPER</a> -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            <!-- if user logged in only show help path -->
             <% if user_signed_in? %>
                <li><%= link_to "HELP", "/path1"  %></li> 
             <% else %> 
                <li><%= link_to "DRIVERS", driver_apply_path %></li>
                <li><%= link_to "HELP", "/path1"  %></li>  
             <% end %>          
         
          </ul>
  
          <!-- users login nav links -->
          <ul class="nav navbar-nav navbar-right" align="right">

            <!-- check if user is signed in a show appropriate links-->
             <% if user_signed_in? %>

              <li class="dropdown">
                 
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">MANAGE <b class="caret"></b></a>

               <ul class="dropdown-menu">
                   <li class="dropdown-header"><%= current_user.email %></li> 
                   <li class="divider"></li>
                    <li><%= link_to 'Book Deliveries', new_bookings_path, :class => 'navbar-link' %> </li>
                    <li><%= link_to 'View Deliveries', bookings_path, :class => 'navbar-link' %> </li>
                    <li class="divider"></li>
                    <li><%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %> </li>
                    
              </ul> </li>
                                
                <li> <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
            <% else %>

              <li><%= link_to "LOGIN", new_user_session_path, :class => 'navbar-link'  %> </li>
              <li> <%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link'  %> </li>
              
            <% end %>

          </ul> <!-- end user loginlinks -->

        </div>
      </div>
    </div>

    
    <div class="container">
      <div class="row">
        
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>


      </div><!--/row-->  

    </div> <!-- /container -->

    <!-- <div class="container">    footer-->
     <% if  current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
        <!-- do nothing -->
     <% else %>
   
      <footer id="myFooter">
        <div class="container">
            <div class="row">
                
                <div class="col-sm-3 myCols">
                    <h5>Get Started</h5>
                    <ul>
                      <li><%= link_to 'Sign Up', new_bookings_path %> </li>
                      <li><%= link_to 'Help', new_bookings_path %> </li>
                      <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Our Company</h5>
                    <ul>
                        <li><%= link_to 'About', new_bookings_path %> </li>
                        <li><%= link_to 'Careers', new_bookings_path %> </li>
                        <li><%= link_to 'Partners', new_bookings_path %> </li>

                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Legal Stuff</h5>
                    <ul>
                       <li><%= link_to 'Privacy Policy', new_bookings_path %> </li>
                      <li><%= link_to ' Terms of Service', new_bookings_path %> </li>
                         
                    </ul>
                </div>

                <div class="col-sm-3 myCols">
                    <h5>Nice Links</h5>
                    <ul>
                       <li><%= link_to 'Log in', new_bookings_path %> </li>
                        <li><%= link_to 'Contact us', new_bookings_path %> </li>
                         <li><%= link_to 'Drivers', new_bookings_path %> </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="social-networks">
            <a href="#" ><i class="fa fa-instagram"></i></a>        
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
             <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>         
        </div>
        <div class="footer-copyright">
            <p>© 2018 Island Dropper Trinidad </p>
        </div>
    </footer>
       <% end %> 
  <!--  </div>  footer end container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h3>Hello Island Dropper</h3>




<div class="container-fluid">

	<!-- <%= image_tag "apple-touch-icon-72x72-precomposed.png" %> -->
  
<!-- <img src="..." class="img-fluid" alt="Responsive image"> -->


</div>